-- 코드를 입력하세요
SELECT PRO.PRODUCT_CODE, SUM(PRO.PRICE * OFF.SALES_AMOUNT) AS SALES
FROM PRODUCT AS PRO
JOIN OFFLINE_SALE AS OFF 
ON (PRO.PRODUCT_ID = OFF.PRODUCT_ID)
GROUP BY PRO.PRODUCT_CODE
ORDER BY SALES DESC, PRO.PRODUCT_CODE ASC