-- 코드를 입력하세요
SELECT ICE.INGREDIENT_TYPE, SUM(FIR.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS FIR
INNER JOIN ICECREAM_INFO AS ICE
ON (FIR.FLAVOR = ICE.FLAVOR)
GROUP BY ICE.INGREDIENT_TYPE 
ORDER BY TOTAL_ORDER 